##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://roseliabanuelos.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /recordinggenderviolence 
# location of code, the full url to your github repository
source-code: https://roseliabanuelos.github.io/recordinggenderviolence/

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Recording Gender Violence 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: decoding the normalization of gender violence in hispanic periodicals 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Gender/Domestic/Intimate Partner violence is the willful intimidation, physical assault, battery, sexual assault, and/or other abusive behavior as part of a systematic pattern of power and control perpetrated by one intimate partner against another. It includes physical violence, sexual violence, and emotional abuse.

Domestic violence happens every minute, mostly behind closed doors.
In America, 24 people per minute experience rape, physical violence, or stalking by an intimate partner.
Nearly 30% of women and 10% of men experience rape, physical violence, or stalking by an intimate partner in America each year.
Roughly 25% of women and 14% of men have been suffered serious physical injuries as a result of physical violence by an intimate partner.
Nearly half of all women and men in America have experienced psychological aggression by an intimate partner.
Females ages 18-34 experience the highest level of intimate partner violence in the United States.
Nearly 50% of female homicides in the United States are committed by former or current intimate partners.
Intimate partner violence has grown by an estimated 40% in Harris County alone during COVID-19. (https://crime-stoppers.org/domestic-violence/)
 This collection explores articles, themes, and patterns within gender violence rhetoric promoted in periodicals from 1830 to 1989. The collection is in Spanish. All documents included can be found in Arte Público Press's database due to the hard work of Recovering the US Hispanic Literary Heritage program. Thank you all for founding, preserving and continuing the legacy. Si se puede. "
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: roseliabanuelos

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: rgv2

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed

theme: jekyll-theme-tactile
